//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ispProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class encounter_main
    {
        public string encounter_id { get; set; }
        public string medical_record_number { get; set; }
        public string hospital_facility { get; set; }
        public string chief_complaint { get; set; }
        public string admission_type { get; set; }
        public string individual_insurance_id { get; set; }
        public System.DateTime admission_date { get; set; }
        public Nullable<System.DateTime> discharge_date { get; set; }
    }
}
