//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ispProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nursing_care_system_assessment_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nursing_care_system_assessment_type()
        {
            this.nursing_care_system_assessment = new HashSet<nursing_care_system_assessment>();
        }
    
        public int care_system_assessment_type_id { get; set; }
        public string care_system_assessment_type_name { get; set; }
        public string wdl_description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nursing_care_system_assessment> nursing_care_system_assessment { get; set; }
    }
}
