//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ispProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nursing_pca_record_history
    {
        public int pca_record_history_id { get; set; }
        public int pca_id { get; set; }
        public int encounter_id { get; set; }
        public Nullable<int> temp_route_type_id { get; set; }
        public Nullable<int> pulse_route_type_id { get; set; }
        public Nullable<int> o_two_delivery_type_id { get; set; }
        public Nullable<int> pain_scale_type_id { get; set; }
        public Nullable<decimal> temperature { get; set; }
        public Nullable<byte> pulse { get; set; }
        public Nullable<byte> respiration { get; set; }
        public Nullable<byte> systolic_blood_pressure { get; set; }
        public Nullable<byte> diastolic_blood_pressure { get; set; }
        public Nullable<byte> pulse_oximetry { get; set; }
        public string oxygen_flow { get; set; }
        public Nullable<byte> pain_level_goal { get; set; }
        public Nullable<byte> pain_level_actual { get; set; }
        public Nullable<System.DateTime> date_vitals_added { get; set; }
        public Nullable<System.DateTime> date_pca_record_modified { get; set; }
        public Nullable<System.DateTime> date_pca_record_orginal { get; set; }
    }
}
