//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ispProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_general_info
    {
        public string medical_record_number { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string mother_maiden_name { get; set; }
        public string gender { get; set; }
        public string social_security_number { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string race { get; set; }
        public string ethnicity { get; set; }
        public string marital_status { get; set; }
        public Nullable<bool> in_city { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_edited { get; set; }
        public Nullable<int> edited_by { get; set; }
    }
}
