//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ispProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userAccount
    {
        public int userAccountId { get; set; }
        public Nullable<int> userId { get; set; }
        public string userName { get; set; }
        public string passwordHash { get; set; }
        public System.DateTime dateCreated { get; set; }
        public System.DateTime dateUpdated { get; set; }
        public Nullable<int> editedBy { get; set; }
        public System.Guid userGuid { get; set; }
    
        public virtual user user { get; set; }
    }
}
