//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ispProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zz_patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zz_patient()
        {
            this.zz_patientRace = new HashSet<zz_patientRace>();
            this.zz_record = new HashSet<zz_record>();
        }
    
        public int patientId { get; set; }
        public string medicalRecordNumber { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public string suffix { get; set; }
        public string maidenName { get; set; }
        public string gender { get; set; }
        public string residenceStreetAddress { get; set; }
        public string residenceAptNo { get; set; }
        public string residenceCity { get; set; }
        public string residenceState { get; set; }
        public string residenceZip { get; set; }
        public string mailingStreetAddress { get; set; }
        public string mailingAptNo { get; set; }
        public string mailingCity { get; set; }
        public string mailingState { get; set; }
        public string mailingZip { get; set; }
        public string SSN { get; set; }
        public string motherSSN { get; set; }
        public string fatherSSN { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public Nullable<System.TimeSpan> birthTime { get; set; }
        public string educationEarned { get; set; }
        public string hispanic { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> weight { get; set; }
        public bool isMarried { get; set; }
        public string birthState { get; set; }
        public string birthCity { get; set; }
        public string birthFacility { get; set; }
        public string priorFirstName { get; set; }
        public string priorMiddleName { get; set; }
        public string priorLastName { get; set; }
        public string priorSuffix { get; set; }
        public bool inCity { get; set; }
        public System.DateTime dateCreated { get; set; }
        public System.DateTime dateUpdated { get; set; }
        public Nullable<int> editedBy { get; set; }
        public string birthCounty { get; set; }
        public string residenceCounty { get; set; }
        public Nullable<int> birthWeight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zz_patientRace> zz_patientRace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zz_record> zz_record { get; set; }
    }
}
