//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ispProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zz_patientRace
    {
        public Nullable<int> patientId { get; set; }
        public int patientRaceId { get; set; }
        public bool white { get; set; }
        public bool black { get; set; }
        public bool indian { get; set; }
        public string tribe { get; set; }
        public bool asianIndian { get; set; }
        public bool chinese { get; set; }
        public bool flipino { get; set; }
        public bool japanese { get; set; }
        public bool korean { get; set; }
        public bool vietnamese { get; set; }
        public string otherAsian { get; set; }
        public bool hawaiian { get; set; }
        public bool guamanian { get; set; }
        public bool samoan { get; set; }
        public string pacificIslander { get; set; }
        public string other { get; set; }
    
        public virtual zz_patient zz_patient { get; set; }
    }
}
