//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ispProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zz_record
    {
        public int entryId { get; set; }
        public Nullable<int> patientId { get; set; }
        public Nullable<int> hospitalId { get; set; }
        public Nullable<int> birthRecordId { get; set; }
    
        public virtual zz_birthRecord zz_birthRecord { get; set; }
        public virtual zz_hospital zz_hospital { get; set; }
        public virtual zz_patient zz_patient { get; set; }
    }
}
