//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ispProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aadmin_data_insurance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aadmin_data_insurance()
        {
            this.patient_insurance = new HashSet<patient_insurance>();
        }
    
        public int Insurance_id { get; set; }
        public string company_name { get; set; }
        public string phone_number { get; set; }
        public string fax { get; set; }
        public string extension { get; set; }
        public string address_street_one { get; set; }
        public string address_street_two { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public System.DateTime date_added { get; set; }
        public Nullable<System.DateTime> date_edited { get; set; }
        public Nullable<int> edited_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient_insurance> patient_insurance { get; set; }
    }
}
