//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ispProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class encounter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public encounter()
        {
            this.nursing_pca_record = new HashSet<nursing_pca_record>();
        }
    
        public int encounter_data_id { get; set; }
        public string encounter_id { get; set; }
        public Nullable<int> attending_doctor_id { get; set; }
        public Nullable<int> facility_id { get; set; }
        public string chief_complaint { get; set; }
        public Nullable<int> admission_type_id { get; set; }
        public Nullable<int> patient_insurance_id { get; set; }
        public System.DateTime admission_date { get; set; }
        public Nullable<System.DateTime> discharge_date { get; set; }
    
        public virtual aadmin_data_admission_type aadmin_data_admission_type { get; set; }
        public virtual hospital_facility hospital_facility { get; set; }
        public virtual patient_insurance patient_insurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nursing_pca_record> nursing_pca_record { get; set; }
    }
}
