//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ispProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HITProjectData_Fall17Entities1 : DbContext
    {
        public HITProjectData_Fall17Entities1()
            : base("name=HITProjectData_Fall17Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aadmin_data_address_type> aadmin_data_address_type { get; set; }
        public virtual DbSet<aadmin_data_admission_type> aadmin_data_admission_type { get; set; }
        public virtual DbSet<aadmin_data_family_relation_type> aadmin_data_family_relation_type { get; set; }
        public virtual DbSet<aadmin_data_insurance> aadmin_data_insurance { get; set; }
        public virtual DbSet<aadmin_data_marital_status> aadmin_data_marital_status { get; set; }
        public virtual DbSet<aadmin_data_patient_ethnicity> aadmin_data_patient_ethnicity { get; set; }
        public virtual DbSet<aadmin_data_patient_gender> aadmin_data_patient_gender { get; set; }
        public virtual DbSet<aadmin_data_patient_name_type> aadmin_data_patient_name_type { get; set; }
        public virtual DbSet<aadmin_data_patient_race> aadmin_data_patient_race { get; set; }
        public virtual DbSet<encounter> encounters { get; set; }
        public virtual DbSet<hospital> hospitals { get; set; }
        public virtual DbSet<hospital_doctor> hospital_doctor { get; set; }
        public virtual DbSet<hospital_facility> hospital_facility { get; set; }
        public virtual DbSet<nursing_care_system_assessment> nursing_care_system_assessment { get; set; }
        public virtual DbSet<nursing_care_system_assessment_history> nursing_care_system_assessment_history { get; set; }
        public virtual DbSet<nursing_care_system_assessment_type> nursing_care_system_assessment_type { get; set; }
        public virtual DbSet<nursing_o_two_delivery_type> nursing_o_two_delivery_type { get; set; }
        public virtual DbSet<nursing_pain_scale_type> nursing_pain_scale_type { get; set; }
        public virtual DbSet<nursing_pca_comment> nursing_pca_comment { get; set; }
        public virtual DbSet<nursing_pca_comment_type> nursing_pca_comment_type { get; set; }
        public virtual DbSet<nursing_pca_record> nursing_pca_record { get; set; }
        public virtual DbSet<nursing_pca_record_history> nursing_pca_record_history { get; set; }
        public virtual DbSet<nursing_pulse_route_type> nursing_pulse_route_type { get; set; }
        public virtual DbSet<nursing_temp_route_type> nursing_temp_route_type { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<patient_address> patient_address { get; set; }
        public virtual DbSet<patient_birth_information> patient_birth_information { get; set; }
        public virtual DbSet<patient_family> patient_family { get; set; }
        public virtual DbSet<patient_insurance> patient_insurance { get; set; }
        public virtual DbSet<patient_name> patient_name { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<userAccount> userAccounts { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<zz_birthRecord> zz_birthRecord { get; set; }
        public virtual DbSet<zz_hospital> zz_hospital { get; set; }
        public virtual DbSet<zz_patient> zz_patient { get; set; }
        public virtual DbSet<zz_patientRace> zz_patientRace { get; set; }
        public virtual DbSet<zz_record> zz_record { get; set; }
        public virtual DbSet<encounter_main> encounter_main { get; set; }
        public virtual DbSet<patient_family_list> patient_family_list { get; set; }
        public virtual DbSet<patient_general_info> patient_general_info { get; set; }
        public virtual DbSet<patient_name_list> patient_name_list { get; set; }
        public virtual DbSet<nursing_pca_comment_history> nursing_pca_comment_history { get; set; }
    }
}
