//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ispProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nursing_pca_comment
    {
        public int pca_comment_id { get; set; }
        public Nullable<int> pca_comment_type_id { get; set; }
        public int pca_id { get; set; }
        public string pca_comment { get; set; }
        public Nullable<System.DateTime> date_comment_added { get; set; }
    
        public virtual nursing_pca_comment_type nursing_pca_comment_type { get; set; }
        public virtual nursing_pca_record nursing_pca_record { get; set; }
    }
}
