//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ispProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nursing_care_system_assessment_history
    {
        public int care_system_assessment_history_id { get; set; }
        public int care_system_assessment_id { get; set; }
        public Nullable<int> care_system_assessment_type_id { get; set; }
        public int pca_id { get; set; }
        public Nullable<bool> wdl_ex { get; set; }
        public string care_system_comment { get; set; }
        public Nullable<System.DateTime> date_pca_record_added { get; set; }
        public Nullable<System.DateTime> date_care_system_added { get; set; }
        public Nullable<System.DateTime> date_care_system_modified { get; set; }
    }
}
