//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ispProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_birth_information
    {
        public int birth_id { get; set; }
        public int patient_id { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string birth_facility { get; set; }
        public string birth_city { get; set; }
        public string birth_state { get; set; }
        public Nullable<int> birth_record_id { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<System.DateTime> date_edited { get; set; }
        public Nullable<int> edited_by { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
